"""
Test the Goertzen-Williamson Gram matrix conjecture at n=4 for V_(3,1).

Conjecture: P_{lambda,1}(q) = char poly of Gram matrix of E_n-image of V_lambda^H
in the seminormal inner product. For lambda=(3,1), expect q^2+4q+1.
"""

import sympy as sp
from sympy import Matrix, Rational, simplify, factor, expand, symbols, eye, zeros

q = symbols('q')

# Young's seminormal form for V_(3,1) of S_4.
# SYTs of shape (3,1):
#   T_a = [[1,2,3],[4]]   contents: 1@(1,1), 2@(1,2), 3@(1,3), 4@(2,1)
#   T_b = [[1,2,4],[3]]   contents: 1@(1,1), 2@(1,2), 3@(2,1), 4@(1,3)
#   T_c = [[1,3,4],[2]]   contents: 1@(1,1), 2@(2,1), 3@(1,2), 4@(1,3)
#
# Axial distance d_t(i) = c(i+1)-r(i+1) - (c(i)-r(i)).
#
# Hoefsmit formula for T_i in seminormal form:
#   If i, i+1 in same row: T_i acts as q on tableau (eigenvalue q).
#   If i, i+1 in same column: T_i acts as -1.
#   Otherwise pair (t, s_i.t) with axial distance d = d_t(i) > 0:
#     T_i e_t   = ((q-1)/(1 - q^{-d})) * e_t + something * e_{s_i t}
# We use the standard (non-symmetric) Hoefsmit form:
#   T_i e_t = (1/[d]) e_t + ([d+1][d-1]/[d]^2)^? e_{s_i t}
# To avoid confusion we use a clean version: for the rational (Murphy/Young) form
# with T_s^2 = (q-1)T_s + q, on the pair (t, s.t) with axial distance d (from t to s.t):
#
#   Let r = [d-1]/[d] = (1-q^{d-1})/(1-q^d).  (here [k]=1+q+...+q^{k-1})
#   Then T_s on span(e_t, e_{st}) has matrix:
#     [[ q*r ,    1     ],
#      [ q - q^2 r^2,  (q-1) - q*r * ... ]]  -- this gets messy.
#
# Cleaner: use the Murphy/Mathas convention. Define for axial distance d>0:
#   alpha = (q-1) + q/[d]_q' where ...
#
# Simplest reliable approach: build T_i as a regular rep on a small basis and
# diagonalize relative to JM elements. For S_4 with basis e_a, e_b, e_c, the
# JM-diagonal seminormal form of T_i (in Mathas's "Iwahori-Hecke Algebras and
# Schur Algebras of the Symmetric Group", Cor 3.20) reads:
#
# Define for each pair (t, s_i t) of standard tableaux differing by s_i, with
# axial distance d = d_t(i):
#     T_i e_t = ((q-1)/(1-q^{-d})) e_t + e_{s_i t}     if s_i t > t
#     T_i e_t = ((q-1)/(1-q^{-d})) e_t + (something) e_{s_i t}  if s_i t < t
# with the "something" chosen so that T_i^2 = (q-1)T_i + q.
#
# To remove ambiguity, we just impose all relations and solve symbolically.
# But that is overkill. Let's use a *direct construction* via Specht polytabloids
# evaluated in the regular representation.
#
# ALTERNATIVE: use the regular representation of H_q(S_4) on the left ideal
# generated by the Young symmetrizer, then project. That is also heavy.
#
# CLEANEST: hard-code the Hoefsmit matrices (well-documented) for shape (3,1).
#
# Hoefsmit (1974) seminormal form. Index basis as (e_a, e_b, e_c).
#
# T_1 acts on the pair (1,2):
#   T_a: 1,2 in same row -> T_1 e_a = q e_a.
#   T_b: 1,2 in same row -> T_1 e_b = q e_b.
#   T_c: 1,2 in same column -> T_1 e_c = -e_c.
# So T_1 = diag(q, q, -1).
#
# T_3 acts on the pair (3,4):
#   T_a: 3@(1,3), 4@(2,1). Different row, different column. Axial dist
#        d = (c(4)-r(4)) - (c(3)-r(3)) = (1-2) - (3-1) = -1 - 2 = -3.
#   T_b: 3@(2,1), 4@(1,3). d = (1-1+row? careful: c(4)-r(4)) - (c(3)-r(3))
#        = (3-1) - (1-2) = 2 - (-1) = 3.
#   T_c: 3,4 in same row -> T_3 e_c = q e_c.
#
# s_3.T_a = swap 3,4 in T_a -> [[1,2,4],[3]] = T_b. So T_a, T_b are paired.
#
# T_2 acts on the pair (2,3):
#   T_a: 2,3 in same row -> T_2 e_a = q e_a.
#   T_b: 2@(1,2), 3@(2,1). d = (1-2)-(2-1) = -1-1 = -2.
#   T_c: 2@(2,1), 3@(1,2). d = (2-1)-(1-2) = 1-(-1) = 2.
# s_2.T_b = [[1,3,4],[2]] = T_c. So T_b, T_c are paired under T_2.
#
# Hoefsmit's formulas for T_i on a paired (t, s_i t) where d = d_t(i):
#   T_i e_t = (q-1)/(1-q^d) * e_t  ...  no wait, I'll use the form from
#   Ram (1997) "Seminormal representations of Weyl groups and Iwahori-Hecke alg":
#   Let a_t = 1/(d_t(i))_q where (k)_q = (q^k - 1)/(q-1) = [k]_q.
#   On the (t, s_i t) block (rows/cols ordered as t, s_i t, with s_i t > t in
#   dominance order for axial distance d > 0):
#       T_i = [[ q a_t,                             q ],
#              [ q - q (a_t)(1 - q a_t)/?? ]]
# This is tangling. Let me just IMPOSE the Hecke relations and solve.

# Solve: find T_1, T_2, T_3 of size 3x3 over Q(q) acting on basis (a,b,c) such that
#   T_1 = diag(q, q, -1)              (forced by row/column placement)
#   T_3 = block diag on (a,b) pair + diag(q) on c
#   T_2 = diag(q) on a + block diag on (b,c) pair
#   Each T_i^2 = (q-1)T_i + q
#   T_1 T_3 = T_3 T_1   (commutation, |1-3|>1)
#   T_1 T_2 T_1 = T_2 T_1 T_2  (braid)
#   T_2 T_3 T_2 = T_3 T_2 T_3  (braid)

print("="*70)
print("Step 1: Build seminormal representation of H_q(S_4) on V_(3,1)")
print("="*70)

T1 = sp.diag(q, q, -1)

# T_3 on pair (a,b): general 2x2 matrix [[A,B],[C,D]] with diag(*, *, q)
A,B,C,D = symbols('A B C D')
# T_3 = [[A,B,0],[C,D,0],[0,0,q]]
# Constraints: T_3^2 = (q-1)T_3 + q on the (a,b) block.
M = Matrix([[A,B],[C,D]])
M2 = M*M
target = (q-1)*M + q*sp.eye(2)
eqs_T3 = []
for i in range(2):
    for j in range(2):
        eqs_T3.append(sp.expand(M2[i,j] - target[i,j]))
# trace condition: A+D = q-1; det = -q.
# Hoefsmit for axial distance d=3 from a to b: standard choice
#   A = (q-1)/(1 - q^{-3}) = (q-1) q^3 / (q^3 - 1)
# From braid analysis (see derivation): on the (a,b) block at axial dist 3,
# diagonal entries are A = -1/(q^2+q+1), D = q^3/(q^2+q+1).
A_val = -sp.Rational(1)/(q**2 + q + 1)
D_val = q**3/(q**2 + q + 1)
# det = A*D - B*C = -q  =>  B*C = A*D + q
BC = sp.simplify(A_val*D_val + q)
# Choose B = 1, then C = BC.
B_val = 1
C_val = sp.simplify(BC)

T3 = sp.Matrix([
    [A_val, B_val, 0],
    [C_val, D_val, 0],
    [0,     0,     q]
])
T3 = sp.simplify(T3)
print("T_3 =")
sp.pprint(T3)

# Verify T_3^2 = (q-1)T_3 + q
chk = sp.simplify(T3*T3 - (q-1)*T3 - q*sp.eye(3))
assert chk == sp.zeros(3,3), f"T_3 quadratic fails: {chk}"
print("T_3 satisfies Hecke quadratic.")

# T_2 on pair (b,c): axial distance d=2 from b to c
# T_2 = diag(q, *, *) with 2x2 block on (b,c)
# On the (b,c) block at axial dist 2, A = -1/(q+1), D = q^2/(q+1).
A2_val = -sp.Rational(1)/(q + 1)
D2_val = q**2/(q + 1)
BC2 = sp.simplify(A2_val*D2_val + q)
B2_val = 1
C2_val = sp.simplify(BC2)

T2 = sp.Matrix([
    [q,      0,      0],
    [0,      A2_val, B2_val],
    [0,      C2_val, D2_val]
])
T2 = sp.simplify(T2)
print("\nT_2 =")
sp.pprint(T2)

chk = sp.simplify(T2*T2 - (q-1)*T2 - q*sp.eye(3))
assert chk == sp.zeros(3,3), f"T_2 quadratic fails: {chk}"
print("T_2 satisfies Hecke quadratic.")

# Verify T_1 T_3 = T_3 T_1
comm13 = sp.simplify(T1*T3 - T3*T1)
assert comm13 == sp.zeros(3,3), f"T_1 T_3 commutation fails:\n{comm13}"
print("T_1 T_3 = T_3 T_1: OK")

# Verify braid T_1 T_2 T_1 = T_2 T_1 T_2
b121 = sp.simplify(T1*T2*T1 - T2*T1*T2)
assert b121 == sp.zeros(3,3), f"Braid 121 fails:\n{b121}"
print("T_1 T_2 T_1 = T_2 T_1 T_2: OK")

# Verify braid T_2 T_3 T_2 = T_3 T_2 T_3
b232 = sp.simplify(T2*T3*T2 - T3*T2*T3)
assert b232 == sp.zeros(3,3), f"Braid 232 fails:\n{b232}"
print("T_2 T_3 T_2 = T_3 T_2 T_3: OK")

print("\n" + "="*70)
print("Step 2: Compute Pi_q = (1+T1)(1+T2)(1+T1)(1+T3)(1+T2)(1+T1)")
print("="*70)
I3 = sp.eye(3)
Pi = (I3+T1)*(I3+T2)*(I3+T1)*(I3+T3)*(I3+T2)*(I3+T1)
Pi = sp.simplify(Pi)
print("Pi_q =")
sp.pprint(Pi)

tr_Pi = sp.simplify(Pi.trace())
tr_Pi_factored = sp.factor(tr_Pi)
print(f"\ntrace(Pi_q) = {tr_Pi_factored}")
expected = q*(1+q)**2*(q**2+4*q+1)
diff = sp.simplify(tr_Pi - expected)
print(f"trace(Pi_q) - q(1+q)^2(q^2+4q+1) = {diff}")
assert diff == 0, "Trace mismatch!"
print("TRACE CHECK PASSED.")

# Eigenvalues of Pi
print("\nEigenvalues of Pi_q on V_(3,1):")
eigs = Pi.eigenvals()
for eig, mult in eigs.items():
    print(f"  {sp.factor(eig)}  (multiplicity {mult})")

print("\n" + "="*70)
print("Step 3: Compute V_(3,1)^H, joint q-eigenspace of T_1 and T_3")
print("="*70)
# H = <s_1, s_3>; H-invariant means T_1 v = q v AND T_3 v = q v
M1 = T1 - q*I3
M3 = T3 - q*I3
combined = M1.col_join(M3)
ker = combined.nullspace()
print(f"dim V_(3,1)^H = {len(ker)}")
assert len(ker) == 1
v = ker[0]
v = sp.simplify(v)
# Clean up: clear denominators
from sympy import together, fraction, lcm
denoms = [fraction(together(x))[1] for x in v]
common = denoms[0]
for d in denoms[1:]:
    common = sp.lcm(common, d)
v = sp.simplify(v * common)
print(f"v = {v.T}")

# Sanity: T1 v - q v == 0, T3 v - q v == 0
assert sp.simplify(T1*v - q*v) == sp.zeros(3,1)
assert sp.simplify(T3*v - q*v) == sp.zeros(3,1)

print("\n" + "="*70)
print("Step 4: E_4 = Pi_q / (1+q)^6, verify rank-1 structure")
print("="*70)
E4 = sp.simplify(Pi / (1+q)**6)
# E4 should have rank 1 with eigenvalue e_lambda/(1+q)^6 = q(1+q)^2(q^2+4q+1)/(1+q)^6
#                                                       = q(q^2+4q+1)/(1+q)^4
eig_E4_expected = q*(q**2+4*q+1)/(1+q)**4
print(f"Expected nonzero eigenvalue of E_4: {eig_E4_expected}")
print("Eigenvalues of E_4:")
for eig, mult in E4.eigenvals().items():
    print(f"  {sp.factor(sp.simplify(eig))}  (mult {mult})")

# Apply E_4 to v
E4v = sp.simplify(E4 * v)
print(f"\nE_4 v = {E4v.T}")
# Since v is in V^H and Pi_q acts on V^H by the eigenvalue e_lambda,
# we expect E_4 v = (e_lambda/(1+q)^6) v.
ratio = sp.simplify(E4v[0] / v[0])
print(f"E_4 v / v (component 0) = {sp.factor(ratio)}")

print("\n" + "="*70)
print("Step 5: GW Gram test")
print("="*70)
print("Two inner products:")
print("  (a) Naive: seminormal basis (a,b,c) Euclidean-orthonormal")
print("  (b) Hecke-invariant: G = diag(g_a, g_b, g_c) with each T_i self-adjoint")

# Naive inner product
def inner(u, w):
    return sp.simplify(sum(u[i]*w[i] for i in range(3)))

vv = inner(v, v)
E4v_E4v = inner(E4v, E4v)
gram_naive = sp.factor(sp.simplify(E4v_E4v / vv))
print(f"\n(a) Naive: <E_4 v, E_4 v> / <v,v> = {gram_naive}")

# Hecke-invariant inner product. Solve G T_i = T_i^T G for diagonal G, gc = 1.
ga = (q**4 + q**2)/(q**2 + q + 1)
gb = (q**3 + q**2 + q)/(q + 1)**2
gc = sp.Integer(1)
G = sp.diag(ga, gb, gc)
# Verify self-adjointness
for Tname, T in [('T1', T1), ('T2', T2), ('T3', T3)]:
    diff = sp.simplify(G*T - T.T*G)
    assert diff == sp.zeros(3,3), f"{Tname} not self-adjoint under G"
print("Verified G T_i = T_i^T G for i=1,2,3.")

def inner_G(u, w):
    return sp.simplify((u.T * G * w)[0,0])

vv_G = inner_G(v, v)
E4v_E4v_G = inner_G(E4v, E4v)
gram_G = sp.factor(sp.simplify(E4v_E4v_G / vv_G))
print(f"\n(b) Hecke-invariant: <v,v>_G = {sp.factor(vv_G)}")
print(f"   <E_4 v, E_4 v>_G = {sp.factor(E4v_E4v_G)}")
print(f"   <E_4 v, E_4 v>_G / <v,v>_G = {gram_G}")
gram = gram_G  # use the natural one for Step 6

print("\n" + "="*70)
print("Step 6: Compare to P_{(3,1),1}(q) = q^2 + 4q + 1")
print("="*70)
target = q**2 + 4*q + 1
print(f"Target P_lambda(q) = {target}")
print(f"Hecke-invariant gram = {sp.factor(gram_G)}")

# Try monomial-in-q-and-(1+q) rescalings
for a in range(-10, 11):
    for b in range(-10, 11):
        cand = sp.simplify(gram_G * (1+q)**a * q**b)
        if sp.simplify(cand - target) == 0:
            print(f"\n*** EXACT MATCH: gram * (1+q)^{a} * q^{b} = q^2+4q+1 ***")

# Also check gram normalised by ||v||^2 in alternative ways
print(f"\n# Other natural ratios:")
print(f"gram / target = {sp.factor(sp.simplify(gram_G / target))}")
print(f"gram / (E_4 eigenvalue) = {sp.factor(sp.simplify(gram_G / (q*(q**2+4*q+1)/(1+q)**4)))}")

# Numerical sanity
for qv in [1, 2, 3]:
    g = float(gram_G.subs(q, qv))
    t = float(target.subs(q, qv))
    print(f"At q={qv}: gram = {g:.6g}, target = {t}, ratio = {g/t:.6g}")
