"""Controls demanded by the brief, plus an exhaustive finite-field classification check."""
import sys, itertools
import sympy as sp
from math import gcd
from engine import all_words, word_to_comp, comp_to_word, partitions, ribbons_maya
from solver import commutator_eqs, commutator_eqs_window, weight_syms, canon

# ---- CONTROL 2: realisability of every occupancy word -----------------------
def realisability(emax=6, nmax=14):
    """Every u in {0,1}^{e-1} must occur as u_M(b,e) for some partition lambda."""
    ok = True
    for e in range(1, emax+1):
        seen = set()
        for n in range(0, nmax+1):
            for lam in partitions(n):
                for mu, u in ribbons_maya(lam, e):
                    seen.add(u)
        miss = set(all_words(e-1)) - seen
        print(f'  e={e}: {len(seen)}/{2**(e-1)} words realised by |lam|<={nmax}'
              + (f'   MISSING {sorted(miss)}' if miss else '   (all)'))
        ok &= not miss
    return ok

# ---- CONTROL 1: calibration to Q147 (height-only weights) -------------------
def calibration(pairs):
    """Substituting height-only weights W(u)=w_{|u|} must return EXACTLY the
    Q147 equation set, i.e. the locus w_z wbar_{u+v+1} + w_u wbar_{v+z} = 0."""
    for (e,f) in pairs:
        w  = {N: sp.Symbol(f'w{N}')  for N in range(e)}
        wb = {N: sp.Symbol(f'x{N}') for N in range(f)}
        W  = {u: w[sum(u)]  for u in all_words(e-1)}
        Wb = {y: wb[sum(y)] for y in all_words(f-1)}
        eqs,_,_ = commutator_eqs_window(e,f,Lw=e+f+1,W=W,Wb=Wb)
        got = {sp.expand(q) for q in eqs} | {sp.expand(-q) for q in eqs}
        # Q147 eq (B): w_z wbar_{u+v+1} + w_u wbar_{v+z}
        want = set()
        for u in range(e):
            for z in range(e):
                for v in range(f-e):
                    if v > f-e-1: continue
                    want.add(sp.expand(w[z]*wb[u+v+1] + w[u]*wb[v+z]))
        missing = {q for q in want if q not in got and sp.expand(-q) not in got}
        # every derived eq must lie in the Q147 ideal generated by `want`
        print(f'  ({e},{f}): derived {len(eqs)} eqs; Q147 relation (B) instances '
              f'contained = {len(want)-len(missing)}/{len(want)}')
        if missing: print('     MISSING:', list(missing)[:4])

# ---- CONTROL 4: e = f must yield no equations -------------------------------
def same_rank(es):
    for e in es:
        W = weight_syms('W', e)
        eqs,ns,ne = commutator_eqs_window(e,e,Lw=2*e+1,W=W,Wb=W)
        print(f'  e=f={e}: states={ns} elements={ne} equations={len(eqs)}')

# ---- the predicted locus ----------------------------------------------------
def gamma_group(d, F):
    """all gamma: Z/d -> F^x with gamma(0)=1 and gamma(x)gamma(-x)=1"""
    units = [x for x in range(1,F)]
    out=[]
    reps=[]; seen={0}
    for x in range(1,d):
        if x in seen: continue
        seen.add(x); seen.add((-x)%d); reps.append(x)
    for vals in itertools.product(units, repeat=len(reps)):
        g={0:1}
        okflag=True
        for x,val in zip(reps,vals):
            g[x]=val; g[(-x)%d]=pow(val,F-2,F)
            if (2*x)%d==0 and (val*val)%F!=1: okflag=False
        if okflag: out.append(dict(g))
    # dedupe
    res=[]; seenk=set()
    for g in out:
        k=tuple(sorted(g.items()))
        if k not in seenk: seenk.add(k); res.append(g)
    return res

def predicted(e, f, F):
    d = gcd(e,f); out=set()
    for g in gamma_group(d, F):
        for al in range(1,F):
            W = tuple((al*  # prod (-gamma(j))^{u_j}
                       __import__('functools').reduce(lambda A,B:(A*B)%F,
                         [((-g[j % d]) % F) for j,uj in enumerate(u,1) if uj], 1)) % F
                      for u in all_words(e-1))
            for be in range(1,F):
                Wb = tuple((be*__import__('functools').reduce(lambda A,B:(A*B)%F,
                         [((-g[j % d]) % F) for j,yj in enumerate(y,1) if yj], 1)) % F
                      for y in all_words(f-1))
                out.add((W,Wb))
    return out

def exhaustive(e, f, F):
    """Brute force over F_F: ALL (W,Wbar) with [R_e,R_f]=0.  Compares to prediction."""
    Ws = weight_syms('W', e); Vs = weight_syms('V', f)
    eqs,_,_ = commutator_eqs_window(e,f,Lw=e+f+1)
    uw = all_words(e-1); yw = all_words(f-1)
    polys = [sp.Poly(q, *( [Ws[u] for u in uw] + [Vs[y] for y in yw] )) for q in eqs]
    terms = [[(m, int(c)%F) for m,c in zip(p.monoms(), p.coeffs())] for p in polys]
    nv = len(uw)+len(yw)
    sols=set()
    for vec in itertools.product(range(F), repeat=nv):
        good=True
        for tl in terms:
            s=0
            for m,c in tl:
                v=c
                for i,ex in enumerate(m):
                    if ex: v=(v*pow(vec[i],ex,F))%F
                s=(s+v)%F
            if s: good=False; break
        if good: sols.add((tuple(vec[:len(uw)]), tuple(vec[len(uw):])))
    zeroW = {(tuple([0]*len(uw)), tuple(v)) for v in itertools.product(range(F),repeat=len(yw))}
    zeroV = {(tuple(v), tuple([0]*len(yw))) for v in itertools.product(range(F),repeat=len(uw))}
    pred = predicted(e,f,F) | zeroW | zeroV
    print(f'  ({e},{f}) over F_{F}: |solutions|={len(sols)}  |predicted|={len(pred)}  '
          f'EQUAL={sols==pred}  extra={len(sols-pred)} missing={len(pred-sols)}')
    if sols-pred: print('     EXTRA sample:', list(sols-pred)[:3])
    if pred-sols: print('     MISSING sample:', list(pred-sols)[:3])
